version: "3.9"

services:

  mysql:
    build:
#      context: docker/mysql
      context: .
#      dockerfile: Dockerfile
      dockerfile: docker/mysql/Dockerfile
    container_name: jworldcup.mysql
    image: jworldcup.mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-osboxes.org}
      MYSQL_USER: worldcup
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-worldcup.org}
      MYSQL_DATABASE: worldcup
    volumes:
      - mysqld:/var/run/mysqld
#      - ./src/test/resources/database/worldcup_test.sql:/docker-entrypoint-initdb.d/2_worldcup_test.sql
#    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-time-zone=UTC']
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    
  phpmyadmin:
    build:
      context: docker/phpmyadmin
      dockerfile: Dockerfile
    container_name: jworldcup.phpmyadmin
    image: jworldcup.phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_SOCKET: /var/run/mysqld/mysqld.sock
##      PMA_HOST: localhost
##      PMA_PORT: 3306
##      PMA_USER: worldcup
##      PMA_PASSWORD: worldcup.org
    volumes:
      - mysqld:/var/run/mysqld
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  rabbitmq:
    build:
      context: docker/rabbitmq
      dockerfile: Dockerfile
      args:
        ENV_POSTFIX: ${ENV_POSTFIX:-}
        RABBITMQ_JWORLDCUP_PASS: ${RABBITMQ_JWORLDCUP_PASS:-}
        RABBITMQ_ADMIN_PASS: ${RABBITMQ_ADMIN_PASS:-}
    image: jworldcup.rabbitmq
    container_name: jworldcup.rabbitmq
    ports:
    - "15672:15672"
    - "15674:15674"
    - "5672:5672"
    - "5671:5671"
    - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_JWORLDCUP_USER:-jwordlcup}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_JWORLDCUP_PASS:-jworldcup}
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: jworldcup.backend
    ports:
    - "8090:8090"
    image: jworldcup.backend
    #command: sh -c 'sleep 30; /wait-for-it.sh -t 0 mysql:3306'
    profiles:
      - production
    depends_on:
      - mysql
      - rabbitmq

## Names our volume
volumes:
  mysqld:
