# Contains application parameters for production environment. Any value can be overriden 
# in other application-{profile} files.

# sensitive secrets are stored in a separated config file, #SECRET labels refer to them here 
#where their values are already obsolete here
spring.config.import: optional:secrets.yml

# Spring
spring:
  application:
    name: jw-backend-sb
  jpa:
    hibernate:
      ddl-auto: none
      connection:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection:
          useUnicode: true
          characterEncoding: UTF-8
        jdbc: 
          time_zone: UTC
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/worldcup?useLegacyDatetimeCode=false # mysql host runs in a docker container
    username: worldcup
    #password: worldcup.org #SECRET
    hikari:
      maximumPoolSize: 20
      transactionIsolation: TRANSACTION_READ_COMMITTED
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  quartz.properties.org.quartz:
    threadPool.threadCount: 3
    jobStore.class: org.quartz.simpl.RAMJobStore
    plugin.jobInitializer:
      class: org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin
      fileNames: quartz-jobs.xml
      failOnFileNotFound: true

# Server
server:
  port: 8090
  servlet:
    context-path: "/jworldcup-api"
    
# Security
jwt:
#  secret: jworldcup-sensitive-secret-key #SECRET
  validity: 
    access: 900 # 15 minutes in seconds
    refresh: 86400 # 24 hours in seconds

# Application
app:
  url: https://worldcup.zematix.hu/
  version:
    number: 1.1.0
    date: 2024-01-13
  shortName: JWorldcup
  emailAddr: jworldcup@zematix.hu
  user:
    expiration:
      candidate.days: 3 # default 0 means no delete of abandoned candidate users at all
      emailModification.days: 3 # default 0 means no delete of abandoned email modifications at all
      passwordReset.days: 3 # default 0 means no delete of abandoned reset passwords at all
      activity.seconds: 300 # 5 minutes
  scheduler.expiration.event.days: 30 # default 0 means no retrieval of match-results from external site at all
  api:
    moduleName: jworldcup
    version: 1.0
  #reCaptcha:
    #secretKey: 6LdAnY0iAAAAALusuamLTrTwloLRU9UJ51IM6u2f #SECRET

# SMTP parameters- Zoho email provider used with generated app specific pwd
mail.smtp:
  host: smtp.zoho.com
  port: 465
  #user: anybody.somebody@domain.dm #SECRET
  #pass: 94Cmyiyy7bMI #SECRET
  auth: true
  starttls.enable: true
  socketFactory.class: javax.net.ssl.SSLSocketFactory
  connectiontimeout: 5000
  timeout: 5000

# RabbitMQ
rabbitMQ:
  host: rabbitmq # rabbitMQ host runs in a docker container
  user: jworldcup
  #password: jworldcup #SECRET

# Logging
logging:
  file.path: logs
  level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework.orm.jpa: TRACE
#    org.springframework.transaction.interceptor: TRACE
#    com.zaxxer.hikari: TRACE
#    com.mysql.cj.jdbc: TRACE
    
#    org.springframework.security.ldap: TRACE
#    org.springframework.ldap: TRACE
#    org.springframework.messaging.simp: WARN
    
#    org.springframework.messaging: DEBUG
#    org.springframework.security.web.authentication: TRACE
#    org.springframework.security.core.session: TRACE
#    org.springframework.cache.interceptor: TRACE
    
    com.zematix.jworldcup.backend: TRACE
