# Contains application parameters for development environment.
# It overrides the parameter values used in application.yml.
# It gets activated by giving option "-Dapplication.environment=development" to JVM

# Spring 
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/worldcup?useLegacyDatetimeCode=false
    username: worldcup
    password: worldcup.org
    hikari:
      maximumPoolSize: 3
      spring:
#  devtools:
#    livereload:
#      enabled: false
#      port: 35729
  quartz :
    #auto-startup: false
    properties.org.quartz:
      plugin.jobInitializer:
        fileNames: quartz-jobs-development.xml

# Application
app:
  url: http://localhost:8090/jworldcup/
  #cheat.dateTime: 2019-06-22 19:00
  #email.enabled: false
  expiredDays.event: 1000

# SMTP parameters - mailtrap email provider used
mail.smtp:
  host: smtp.mailtrap.io
  port: 2525
  user: 16febbd3b2dff0
  pass: 4b1dc44f26f800

# Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: TRACE
#    org.springframework.transaction.interceptor: TRACE
#    com.zaxxer.hikari: TRACE
    
#    org.springframework.security.ldap: TRACE
#    org.springframework.ldap: TRACE
#    org.springframework.messaging.simp: WARN
    
#    org.springframework.messaging: DEBUG
#    org.springframework.security.web.authentication: TRACE
#    org.springframework.security.core.session: TRACE
#    org.springframework.cache.interceptor: TRACE
    
    com.zematix.jworldcup.backend: TRACE

