# Contains application parameters for production environment. Any value can be overriden 
# in other application-{profile} files.

# sensitive secrets are stored in a separated config file, #SECRET labels refer to them here 
#where their values are already obsolete here
spring.config.import: optional:secrets.yml

# Spring
spring:
  application:
    name: jw-backend-sb
  jpa:
    hibernate:
      ddl-auto: none
      connection:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection:
          useUnicode: true
          characterEncoding: UTF-8
        jdbc: 
          time_zone: UTC
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/worldcup?useLegacyDatetimeCode=false # mysql host runs in an docker image
    username: worldcup
    #password: worldcup.org #SECRET
    hikari:
      maximumPoolSize: 20
      transactionIsolation: TRANSACTION_READ_COMMITTED
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  main:
    allow-bean-definition-overriding: true
  quartz.properties.org.quartz:
    threadPool.threadCount: 3
    jobStore.class: org.quartz.simpl.RAMJobStore
    plugin.jobInitializer:
      class: org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin
      fileNames: quartz-jobs.xml
      failOnFileNotFound: true

# Server
server:
  port: 8090
  servlet:
    context-path: "/jworldcup"
    
# Security
#jwt.secret: jworldcup-sensitive-secret-key #SECRET

# Application
app:
  url: https://worldcup.zematix.hu/
  version:
    number: 0.6.0
    date: 2021-04-29
  shortName: JWorldcup
  emailAddr: jworldcup@zematix.hu
  user.candidate.expire.days: 3
  api:
    moduleName: jworldcup
    version: 1.0
  expiredDays:
    event: 30 # default 0 means no retrieval of match-results from external site at all
    user:
      candidate: 3 # default 0 means no delete of abandoned candidate users at all
      emailModification: 3 # default 0 means no delete of abandoned email modifications at all
      passwordReset: 3 # default 0 means no delete of abandoned reset passwords at all
  #reCaptcha:
    #secretKey: 6LdAnY0iAAAAALusuamLTrTwloLRU9UJ51IM6u2f #SECRET

# Cookie
cookie.maxAge: 1209600

# SMTP parameters- Zoho email provider used with generated app specific pwd
mail.smtp:
  host: smtp.zoho.com
  port: 465
  #user: branyiczky.zsolt@zematix.hu #SECRET
  #pass: 94Cmyiyy7bMI #SECRET
  auth: true
  starttls.enable: true
  socketFactory.class: javax.net.ssl.SSLSocketFactory
  connectiontimeout: 5000
  timeout: 5000

# RabbitMQ
rabbitMQ:
  #user: guest #SECRET
  #password: guest #SECRET